language: php
dist: trusty
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - hhvm
    - hhvm-3.6
    - hhvm-3.12
    - hhvm-3.24
    - hhvm-nightly
    - nightly
matrix:
    include:
        - php: hhvm
        env: PHPUNIT_VERSION=5.7
        - php: hhvm-nightly
        env: PHPUNIT_VERSION=5.7
    allow_failures:
        - php: 7.3
        - php: hhvm
        - php: hhvm-nightly
        - php: nightly

before_script:
    - if [[ $PHPUNIT_VERSION != "" ]]; then composer require "phpunit/phpunit:$PHPUNIT_VERSION"; fi
    - composer update

script: ./vendor/bin/phpunit -c tests/phpunit.xml
